export const initialState = {
  posts: {
    data: [
      {
        id: '1',
        title: 'Ad number 1',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        datePublication: '2021.3.20',
        dateLastUpdate: '2021.3.21',
        email: 'example@gmail.com',
        status: 'published',
        photo: 'https://placeimg.com/640/480/nature/1',
        price: '1000',
        phone: '111222333',
        location: 'Asbru',
      },
      {
        id: '2',
        title: 'Ad number 2',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        datePublication: '2021.3.26',
        dateLastUpdate: '2021.3.29',
        email: 'marian@gmail.com',
        status: 'draft',
        photo: 'https://placeimg.com/640/480/nature/2',
        price: '550',
        phone: '123456789',
        location: 'Wrocław',
      },
      {
        id: '3',
        title: 'Ad number 3',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        datePublication: '2021.3.30',
        dateLastUpdate: '2021.3.30',
        email: 'helena@gmail.com',
        status: 'closed',
        photo: 'https://placeimg.com/640/480/nature/3',
        price: '4500',
        phone: '123123123',
        location: 'Wrocław',
      },
      {
        id: '4',
        title: 'Ad number 4',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        datePublication: '2021.4.01',
        dateLastUpdate: '2021.4.05',
        email: 'boczek@gmail.com',
        status: 'closed',
        photo: 'https://placeimg.com/640/480/nature/4',
        price: '5',
        phone: '111222111',
        location: 'Oława',
      },
      {
        id: '5',
        title: 'Ad number 5',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        datePublication: '2021.4.04',
        dateLastUpdate: '2021.4.10',
        email: 'halinka@gmail.com',
        status: 'published',
        photo: 'https://placeimg.com/640/480/nature/5',
        price: '999',
        phone: '123321123',
        location: 'Reykjavik',
      },
      {
        id: '6',
        title: 'Ad number 6',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        datePublication: '2021.4.11',
        dateLastUpdate: '2021.4.11',
        email: 'ferdek@gmail.com',
        status: 'draft',
        photo: 'https://placeimg.com/640/480/nature/6',
        price: '20',
        phone: '111000111',
        location: 'Dublin',
      },
    ],
    loading: {
      active: false,
      error: false,
    },
  },
};
